# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: './CrossSiteWebhooks'

- task: CmdLine@2
  inputs:
    script: |
      gulp bundle --ship
      gulp package-solution --ship

- task: Gulp@1
  inputs:
    gulpFile: 'gulpfile.js'
    targets: 'package-solution --ship'
    enableCodeCoverage: false
    workingDirectory: './CrossSiteWebhooks'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/drop'
    ArtifactName: 'drop'
    publishLocation: 'Container'
